// Generated by gencpp from file ferns_detector/Detection.msg
// DO NOT EDIT!


#ifndef FERNS_DETECTOR_MESSAGE_DETECTION_H
#define FERNS_DETECTOR_MESSAGE_DETECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ferns_detector/DetectedPoint.h>
#include <ferns_detector/DetectedPoint.h>
#include <ferns_detector/DetectedPoint.h>
#include <ferns_detector/DetectedPoint.h>

namespace ferns_detector
{
template <class ContainerAllocator>
struct Detection_
{
  typedef Detection_<ContainerAllocator> Type;

  Detection_()
    : header()
    , model()
    , top_left()
    , top_right()
    , bottom_right()
    , bottom_left()  {
    }
  Detection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , model(_alloc)
    , top_left(_alloc)
    , top_right(_alloc)
    , bottom_right(_alloc)
    , bottom_left(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _model_type;
  _model_type model;

   typedef  ::ferns_detector::DetectedPoint_<ContainerAllocator>  _top_left_type;
  _top_left_type top_left;

   typedef  ::ferns_detector::DetectedPoint_<ContainerAllocator>  _top_right_type;
  _top_right_type top_right;

   typedef  ::ferns_detector::DetectedPoint_<ContainerAllocator>  _bottom_right_type;
  _bottom_right_type bottom_right;

   typedef  ::ferns_detector::DetectedPoint_<ContainerAllocator>  _bottom_left_type;
  _bottom_left_type bottom_left;





  typedef boost::shared_ptr< ::ferns_detector::Detection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ferns_detector::Detection_<ContainerAllocator> const> ConstPtr;

}; // struct Detection_

typedef ::ferns_detector::Detection_<std::allocator<void> > Detection;

typedef boost::shared_ptr< ::ferns_detector::Detection > DetectionPtr;
typedef boost::shared_ptr< ::ferns_detector::Detection const> DetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ferns_detector::Detection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ferns_detector::Detection_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ferns_detector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ferns_detector': ['/home/genta/Desktop/robotics_project/catkin_ws/src/ferns_detector/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ferns_detector::Detection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ferns_detector::Detection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ferns_detector::Detection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ferns_detector::Detection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ferns_detector::Detection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ferns_detector::Detection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ferns_detector::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32608db182e57959f8cbb42d13b3f08c";
  }

  static const char* value(const ::ferns_detector::Detection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32608db182e57959ULL;
  static const uint64_t static_value2 = 0xf8cbb42d13b3f08cULL;
};

template<class ContainerAllocator>
struct DataType< ::ferns_detector::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ferns_detector/Detection";
  }

  static const char* value(const ::ferns_detector::Detection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ferns_detector::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header 								header\n\
string                              model\n\
DetectedPoint 						top_left\n\
DetectedPoint 						top_right\n\
DetectedPoint 						bottom_right\n\
DetectedPoint 						bottom_left\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: ferns_detector/DetectedPoint\n\
int32 												  x\n\
int32 													y\n\
";
  }

  static const char* value(const ::ferns_detector::Detection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ferns_detector::Detection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.model);
      stream.next(m.top_left);
      stream.next(m.top_right);
      stream.next(m.bottom_right);
      stream.next(m.bottom_left);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Detection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ferns_detector::Detection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ferns_detector::Detection_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "model: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.model);
    s << indent << "top_left: ";
    s << std::endl;
    Printer< ::ferns_detector::DetectedPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.top_left);
    s << indent << "top_right: ";
    s << std::endl;
    Printer< ::ferns_detector::DetectedPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.top_right);
    s << indent << "bottom_right: ";
    s << std::endl;
    Printer< ::ferns_detector::DetectedPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.bottom_right);
    s << indent << "bottom_left: ";
    s << std::endl;
    Printer< ::ferns_detector::DetectedPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.bottom_left);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FERNS_DETECTOR_MESSAGE_DETECTION_H
